// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeMoOougX2vEprYrW2jp9-vS49h5FyAgQ',
    appId: '1:773514102852:android:a72ad8a48f69d325de1411',
    messagingSenderId: '773514102852',
    projectId: 'dinevio-app',
    storageBucket: 'dinevio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mU9UPeyFZp9tMx81ABGM1vrTtEhEjXU',
    appId: '1:773514102852:ios:c4dc8c41117170aade1411',
    messagingSenderId: '773514102852',
    projectId: 'dinevio-app',
    storageBucket: 'dinevio-app.firebasestorage.app',
    iosBundleId: 'com.mytaxi.customers',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTM14vfTpBZ7SwmFiKbhhEyjrBv24D3fY',
    appId: '1:773514102852:web:2f0f581fac87e126de1411',
    messagingSenderId: '773514102852',
    projectId: 'dinevio-app',
    authDomain: 'dinevio-app.firebaseapp.com',
    storageBucket: 'dinevio-app.firebasestorage.app',
  );

}